#! /bin/sh
/bin/busybox echo "==== Init ramfs ===="
/bin/busybox mkdir -p /sbin /var/log /run /proc /sys /tmp /dev /usr/bin /usr/sbin
/bin/busybox --install -s
mount -t sysfs sysfs /sys
mount -t proc procfs /proc
mdev -s
ls /dev
date
test -b /dev/vda2 || exec /bin/sh
mkdir -p /mnt
mount /dev/vda2 /mnt || exec /bin/sh
exec /bin/sh
